# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(upload_to='images/faculty/'),
        ),
    ]
