# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0002_auto_20160226_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='facultytitle',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='publications',
            name='starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publications',
            name='year',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
